"""empty message

Revision ID: 90c2b7481fea
Revises: 9404352e278e
Create Date: 2016-03-25 08:26:43.698650

"""

# revision identifiers, used by Alembic.
revision = '90c2b7481fea'
down_revision = '9404352e278e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('todo', 'isComplete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.alter_column('todo', 'isComplete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('todo', 'user_id')
    ### end Alembic commands ###
