"""empty message

Revision ID: bef6934b21f8
Revises: c4284f31c4e1
Create Date: 2016-03-24 11:25:17.278226

"""

# revision identifiers, used by Alembic.
revision = 'bef6934b21f8'
down_revision = 'c4284f31c4e1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('item', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('isComplete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
