"""empty message

Revision ID: c4284f31c4e1
Revises: 4d9b5429f2a8
Create Date: 2016-03-24 11:01:51.579702

"""

# revision identifiers, used by Alembic.
revision = 'c4284f31c4e1'
down_revision = '4d9b5429f2a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'isComplete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=120),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=120),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('todo', 'isComplete',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
